/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ArchivedSessionReadValue, SessionArchiveDeleteAllValue, SessionArchiveListValue, SessionArchiveMutationValue, SessionArchiveResult, SessionArchiveSessionRequest } from '@dsh-undo/rollback-archive/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73657373696f6e41726368697665 {
    delete: (request: SessionArchiveSessionRequest) => Promise<RemoteResult<SessionArchiveResult<SessionArchiveMutationValue>>>
    deleteAll: () => Promise<RemoteResult<SessionArchiveDeleteAllValue>>
    list: () => Promise<RemoteResult<SessionArchiveListValue>>
    read: (request: SessionArchiveSessionRequest) => Promise<RemoteResult<SessionArchiveResult<ArchivedSessionReadValue>>>
    restore: (request: SessionArchiveSessionRequest) => Promise<RemoteResult<SessionArchiveResult<SessionArchiveMutationValue>>>
    tombstone: (sessionId: SessionId) => Promise<RemoteResult<SessionArchiveResult<SessionArchiveMutationValue>>>
    untombstone: (sessionId: SessionId) => Promise<RemoteResult<SessionArchiveResult<SessionArchiveMutationValue>>>
  }
  interface TypertRemoteMap {
    'sessionArchive/delete': (request: SessionArchiveSessionRequest) => Promise<RemoteResult<SessionArchiveResult<SessionArchiveMutationValue>>>
    'sessionArchive/deleteAll': () => Promise<RemoteResult<SessionArchiveDeleteAllValue>>
    'sessionArchive/list': () => Promise<RemoteResult<SessionArchiveListValue>>
    'sessionArchive/read': (request: SessionArchiveSessionRequest) => Promise<RemoteResult<SessionArchiveResult<ArchivedSessionReadValue>>>
    'sessionArchive/restore': (request: SessionArchiveSessionRequest) => Promise<RemoteResult<SessionArchiveResult<SessionArchiveMutationValue>>>
    'sessionArchive/tombstone': (sessionId: SessionId) => Promise<RemoteResult<SessionArchiveResult<SessionArchiveMutationValue>>>
    'sessionArchive/untombstone': (sessionId: SessionId) => Promise<RemoteResult<SessionArchiveResult<SessionArchiveMutationValue>>>
  }
  interface TypertRemoteNamespaceMap {
    'sessionArchive': TypertRemoteNamespace$73657373696f6e41726368697665
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
