/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ConversationAdmissionFailureRequest, ConversationAdmissionFailureValue, ConversationArchiveActionRequest, ConversationArchiveActionValue, ConversationCurrentRequest, ConversationRevokePairRequest, ConversationRevokePairValue, ConversationRevokeRequest, ConversationRollbackChildRequest, ConversationUndoLatestRequest, ConversationUndoLayerInspectionRequest, ConversationUndoLayerInspectionValue, ConversationUndoLayersRequest, ConversationUndoLayerValue, ConversationUndoResult, ConversationUndoThroughRequest } from '@dsh-undo/rollback-undo/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636f6e766572736174696f6e556e646f {
    admissionFailure: (request: ConversationAdmissionFailureRequest) => Promise<RemoteResult<ConversationAdmissionFailureValue | undefined>>
    archiveAction: (request: ConversationArchiveActionRequest) => Promise<RemoteResult<ConversationArchiveActionValue>>
    current: (request: ConversationCurrentRequest) => Promise<RemoteResult<ConversationUndoResult>>
    inspectLayer: (request: ConversationUndoLayerInspectionRequest) => Promise<RemoteResult<ConversationUndoLayerInspectionValue>>
    layers: (request: ConversationUndoLayersRequest) => Promise<RemoteResult<readonly ConversationUndoLayerValue[]>>
    revoke: (request: ConversationRevokeRequest) => Promise<RemoteResult<ConversationUndoResult>>
    revokePair: (request: ConversationRevokePairRequest) => Promise<RemoteResult<ConversationRevokePairValue | undefined>>
    rollbackChild: (request: ConversationRollbackChildRequest) => Promise<RemoteResult<{ rollbackSessionId: SessionId; } | undefined>>
    undoLatest: (request: ConversationUndoLatestRequest) => Promise<RemoteResult<ConversationUndoResult>>
    undoThrough: (request: ConversationUndoThroughRequest) => Promise<RemoteResult<ConversationUndoResult>>
  }
  interface TypertRemoteMap {
    'conversationUndo/admissionFailure': (request: ConversationAdmissionFailureRequest) => Promise<RemoteResult<ConversationAdmissionFailureValue | undefined>>
    'conversationUndo/archiveAction': (request: ConversationArchiveActionRequest) => Promise<RemoteResult<ConversationArchiveActionValue>>
    'conversationUndo/current': (request: ConversationCurrentRequest) => Promise<RemoteResult<ConversationUndoResult>>
    'conversationUndo/inspectLayer': (request: ConversationUndoLayerInspectionRequest) => Promise<RemoteResult<ConversationUndoLayerInspectionValue>>
    'conversationUndo/layers': (request: ConversationUndoLayersRequest) => Promise<RemoteResult<readonly ConversationUndoLayerValue[]>>
    'conversationUndo/revoke': (request: ConversationRevokeRequest) => Promise<RemoteResult<ConversationUndoResult>>
    'conversationUndo/revokePair': (request: ConversationRevokePairRequest) => Promise<RemoteResult<ConversationRevokePairValue | undefined>>
    'conversationUndo/rollbackChild': (request: ConversationRollbackChildRequest) => Promise<RemoteResult<{ rollbackSessionId: SessionId; } | undefined>>
    'conversationUndo/undoLatest': (request: ConversationUndoLatestRequest) => Promise<RemoteResult<ConversationUndoResult>>
    'conversationUndo/undoThrough': (request: ConversationUndoThroughRequest) => Promise<RemoteResult<ConversationUndoResult>>
  }
  interface TypertRemoteNamespaceMap {
    'conversationUndo': TypertRemoteNamespace$636f6e766572736174696f6e556e646f
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
